# Starter pipeline

trigger:
- master

pool:
  name: lxn-agent-pool

stages:
- stage: Build
  jobs:
  - job: ABE_Job
    steps:
    - bash: |
       pwd
       sudo mkdir build 
       cd ${sagHome}/common/AssetBuildEnvironment/bin/
       sudo ./build.sh \
        -Dsag.install.dir=${sagHome} \
        -Dbuild.source.dir=./source/IS/ \
        -Dbuild.output.dir=./build/ \
        -Denable.build.IS=true \
        -Dbuild.version=1.0
       
       
       cd build
       ls -ltr
    displayName: 'Create ABE Build'
- stage: Stage
  jobs:
  - job: Stage_Deploy_Job
    steps:
      - script: echo Hello, DevJob1!
    displayName: 'Deploy_Stage_Env'


         