# Starter pipeline

variables:
  sagHome: '/opt/softwareag/is106'

trigger:
- master

pool:
  name: lxn-agent-pool

stages:
- stage: Build
  jobs:
  - job: ABE_Job
    steps:
    - bash: |
       echo $(Agent.BuildDirectory)
       echo ${{parameters.sagHome}}
       BuildDir=$(Agent.BuildDirectory)
       echo $BuildDir
       cd ${{parameters.sagHome}}/common/AssetBuildEnvironment/bin/
       sudo ./build.sh \
        -Dsag.install.dir=${{parameters.sagHome}} \
        -Dbuild.source.dir=$BuildDir/s/source/IS/ \
        -Dbuild.output.dir=$BuildDir/build/ \
        -Denable.build.IS=true \
        -Dbuild.version=1.0
       
       
       cd $BuildDir/build/
       ls -ltr
    displayName: 'Create ABE Build'

- stage: Stage
  jobs:
  - job: Stage_Deploy_Job
    steps:
      - script: echo Hello, DevJob1!
    displayName: 'Deploy_Stage_Env'

- stage: CleanUp
  jobs:
  - job: Cleanup_Job
    steps:
    - bash: |
       cd $(Agent.BuildDirectory)
       rm -rf *
         